# AUTOGENERATED! DO NOT EDIT! File to edit: ../02_features.ipynb.

# %% auto 0
__all__ = []

# %% ../02_features.ipynb 3
## helper functions
# import logging

# from pathlib import Path

# import pandas as pd
# import numpy as np


# def get_locus_values(s):
#     from roux.lib.str import get_bracket

#     d = dict(
#         chrom=s.split(":")[0],
#         start=int(s.split(":")[1].split("-")[0]),
#         end=int(s.split("-")[1].split("(")[0]),
#         strand=get_bracket(s),
#     )
#     return d


# def get_locus_object(
#     chrom,
#     start,
#     end,
#     strand,
# ):
#     from pyensembl.locus import Locus

#     return Locus(
#         contig=chrom,
#         start=start,
#         end=end,
#         strand="-" if strand == -1 else "+" if strand in [1, "", None] else strand,
#     )


# def unify_the_strands(x):
#     x.strand = "+"
#     return x
